#!/usr/bin/env python
LOCAL = "/home/themylogin/Storage/Screenshots"

import gtk
import sys

count = 0
def handle_owner_change(clipboard, event):
    global count
    count += 1
    if count > 1:
        sys.exit(0)

image = gtk.gdk.pixbuf_new_from_file(LOCAL + "/" + open(LOCAL + "/.last", "r").read())
clipboard = gtk.clipboard_get()
clipboard.connect("owner-change", handle_owner_change)
clipboard.set_image(image)
clipboard.store()
gtk.main()
